AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/**/*
    - bower_components/**/*
    - db/schema.rb
    - node_modules/**/*
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
